### ISSUE TITLE
Installing cityflow

### ISSUE THREAD

**Issue by Sdinesh7** [cityflow-project/CityFlow#101]
I am trying to install cityflow on Mac OS. Instead of using a docker, I am trying to build from the source for which I need to install CPP dependencies but as I am using mac OS I cannot use apt and install build essential. Will I be facing any problems if I continue without installing CPP dependencies or should I prefer installing using docker

**Comment by soodoshll** [comment]
I think the only dependency you need is `cmake` if you have already installed mac commandline tools. You can use `Homebrew` or other package managers to install it.

**Comment by Sdinesh7** [comment]
Thanks!!
