### ISSUE TITLE
How to access functions like getPoint() which are in Vehicle class

### ISSUE THREAD

**Issue by Sdinesh7** [cityflow-project/CityFlow#103]
I tried adding this part of code to cityflow.cpp 

<img width="439" alt="Screen Shot 2020-06-25 at 10 05 06 AM" src="https://user-images.githubusercontent.com/26570708/85734904-5fcb5980-b6cb-11ea-88d4-6d4db54e7379.png">

<img width="552" alt="Screen Shot 2020-06-22 at 5 06 32 PM" src="https://user-images.githubusercontent.com/26570708/85734790-46c2a880-b6cb-11ea-9e1d-61bb87549660.png">

Functions in engine class can be accessed by starting the engine at above. But how can I access functions like getPoint()

<img width="650" alt="Screen Shot 2020-06-25 at 10 06 38 AM" src="https://user-images.githubusercontent.com/26570708/85735370-986b3300-b6cb-11ea-95c1-01854d79275e.png">

<img width="577" alt="Screen Shot 2020-06-25 at 10 09 09 AM" src="https://user-images.githubusercontent.com/26570708/85735751-f0099e80-b6cb-11ea-94ab-11c632d71930.png">

**Comment by soodoshll** [comment]
I think one solution is to write a new function which return a std::vector<double> with size of 2 to represent the point.

**Comment by Sdinesh7** [comment]
Do you mean to write a function in the vehicle class in vehicle.cpp file. Even after that, I can't seem to figure out how to use any of those functions like getMinGap(), getYeildDistance(), or any of those functions in vehicle class to use in my script file like I use the functions in engine class.

**Comment by Sdinesh7** [comment]
@soodoshll Please can you make it more clear. I can't seem to figure it out.

**Comment by zhc134** [comment]
If you want to use the method in Vehicle class, you need to call it on the Vehicle object instead of Engine object.
That means, you need to add a method to Engine first, which return a vector of vehicles (In python, list of vehicle objects). Then you can call the method on each vehicle object.

**Comment by zhc134** [comment]
@Sdinesh7 If you want to use the method in Vehicle class, you need to call it on the Vehicle object instead of Engine object.
That means, you need to add a method to Engine first, which return a vector of vehicles (In python, list of vehicle objects). Then you can call the method on each vehicle object.
