### ISSUE TITLE
hi 大佬们，方便加微信么，有些问题实搞不懂啊，我在加载roadnet 的时候老出现 打开文件失败，读取文件失败的情况

### ISSUE THREAD

**Issue by zongzidedandan** [cityflow-project/CityFlow#105]
it seems that my PATH is right when jsonFilename has been printouted . Could you help me check that ? if it is convenient I want get your weChat(mine 18366188149) number and ask more thing about cityflow . Anyway,  thank you guys so much!

BR
Information about my ENV

1.env：win10 Anaconda3 python3.7 
cityflow                    0.1                       pypi_0    pypi
cmake                     3.17.3                   pypi_0    pypi
2.IDE： PyCharm:
config files
config_dict = {
            "interval": 1.0,
            "warning": True,
            "seed": 0,
            "dir": "config/",
            "roadnetFile": "roadnet/roadnet.json",
            "flowFile": "flow/flow.json",
            "rlTrafficLight": True,
            "laneChange": True,
            "saveReplay": True,
            "roadnetLogFile":"web/roadnet.json",
            "replayLogFile": "web/roadnet_relay.txt"
        }
3.Project folder：
6/23/2020  10:41 AM    <DIR>          build
07/23/2020  10:16 AM    <DIR>          CityFlow.egg-info
06/22/2020  01:51 PM               2,599 CMakeLists.txt
07/22/2020  05:48 PM    <DIR>          **config**
06/23/2020  10:41 AM    <DIR>          dist
06/22/2020  01:51 PM               689 Dockerfile
06/22/2020  01:51 PM    <DIR>          docs
06/22/2020  01:51 PM    <DIR>          examples
06/22/2020  01:51 PM    <DIR>          extern
06/24/2020  03:02 PM    <DIR>          frontend
06/22/2020  01:51 PM            11,556 LICENSE.txt
06/23/2020  05:27 PM    <DIR>          My_city
06/23/2020  04:55 PM    <DIR>          Network
06/22/2020  01:51 PM             2,640 README.rst
07/21/2020  04:55 PM    <DIR>          RL light traffic
06/22/2020  01:51 PM             2,600 setup.py
06/22/2020  01:51 PM    <DIR>          src
06/22/2020  01:51 PM    <DIR>          tests
06/22/2020  01:51 PM    <DIR>          tools

4.C++ printout 
       RoadNet::loadFromJson(std::string jsonFileName) {
        rapidjson::Document document;
        std::cerr << "\n--------------------------------------\n" << std::endl;
        std::cerr << jsonFileName << std::endl;
        std::cerr << "\n--------------------------------------\n" << std::endl;
5.err log:
--------------------------------------

config/roadnet/roadnet.json

--------------------------------------

cannot open roadnet file
loading roadnet file error!
load config failed!

**Comment by Sheagu** [comment]
+1

**Comment by Siaaa-3** [comment]
哈喽 
请问你解决cityflow这个画图的问题了吗？

**Comment by Sheagu** [comment]
试试翻墙吧，对我有效

**Comment by Siaaa-3** [comment]
不过我好像是加载文件的时候没有出问题，然后它 drawing roadnet的时候就出问题了。。而且我选的确实也是roadlognet文件，不知道哪错了


想再请问一下你当时用的是Ubuntu系统，Firefox浏览器吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月10日(周五) 晚上6:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cityflow-project/CityFlow] hi 大佬们，方便加微信么，有些问题实搞不懂啊，我在加载roadnet 的时候老出现 打开文件失败，读取文件失败的情况 (#105)




 
试试翻墙吧，对我有效
