### ISSUE TITLE
A bug in converter

### ISSUE THREAD

**Issue by X3nOph0N** [cityflow-project/CityFlow#107]
in tools/converter/converter.py line 399 ,this sentence
`for phase,duration in tls_dict[nodeid]._programs['0']._phases:`
 will not work since there is no __iter__(self) and __next__(self) in  sumo(Version 1.7.0). 
Besides, there is more than two elements to unpack and this can lead to error too.
Use the fllowing sentence 
`for current_phase in tls_dict[nodeid]._programs['0']._phases :`
,modify the relative variable in line 399 to line 420  and add __iter__,__next__ in Sumo/tools/sumolib/net/__init__.py can fix it.

**Comment by guiga-mertens** [comment]
Can you explain a little more detailed how to fix that issue? Couldn't fix it

**Comment by X3nOph0N** [comment]
> Can you explain a little more detailed how to fix that issue? Couldn't fix it

You can find the working verision code in my  respositories.
Once again, remember to add two function `__iter(self)__ `and  `__next(self)__` in `Sumo/tools/sumoliv/net/__init.py` which are essential for python to finish the for in loop.

**Comment by Salchipao** [comment]
> > Can you explain a little more detailed how to fix that issue? Couldn't fix it
> 
> You can find the working verision code in my respositories.
> Once again, remember to add two function `__iter(self)__ `and `__next(self)__` in `Sumo/tools/sumoliv/net/__init.py` which are essential for python to finish the for in loop.

**Comment by Salchipao** [comment]
> > Can you explain a little more detailed how to fix that issue? Couldn't fix it
> 
> You can find the working verision code in my respositories.
> Once again, remember to add two function `__iter(self)__ `and `__next(self)__` in `Sumo/tools/sumoliv/net/__init.py` which are essential for python to finish the for in loop.

I'm going through the same problem. Where should I add these functions in __init__.py?

**Comment by X3nOph0N** [comment]
> I'm going through the same problem. Where should I add these functions in `__init__.py`?
Well... exactly in `Sumo/tools/sumolib/net/__init.py class Phase`.
You will most likely to see this class in line 93.

**Comment by X3nOph0N** [comment]
I think that the discussion above can clearly solve this problem now, so I decided to close it. If anyone watching this still have trouble fixing it, you can just check the working version in my respositories.(I also forked sumo, so you can check how I fixed it there, it's quiet simple)
