### ISSUE TITLE
what the phase means in CityFlow?

### ISSUE THREAD

**Issue by LuckyLeeLL** [cityflow-project/CityFlow#108]
Sorry, I cannot know how to set the traffic light with yellow?

**Comment by X3nOph0N** [comment]
Well……I guess there is no option to set it yellow since the phase can only determine if the road link is avaliable for the vehicles.
If there is, I'm also curious about it.

**Comment by zhc134** [comment]
Currently, we don't have a yellow phase. 

Vehicles will go through the intersection even it's red light, if it cannot perform a full stop before the intersection.
During our experiment, we use an all-red phase to serve as a buffer time.

Please check https://github.com/zhc134/tlc-baselines, where we provide OpenAI Gym compatible environments for traffic light control scenario and a bunch of baseline methods.

**Comment by LuckyLeeLL** [comment]
> Currently, we don't have a yellow phase.
> 
> Vehicles will go through the intersection even it's red light, if it cannot perform a full stop before the intersection.
> During our experiment, we use an all-red phase to serve as a buffer time.
> 
> Please check https://github.com/zhc134/tlc-baselines, where we provide OpenAI Gym compatible environments for traffic light control scenario and a bunch of baseline methods.

I understand what you mean, thank you very much
