### ISSUE TITLE
Error installing cityflow

### ISSUE THREAD

**Issue by ClearloveWei** [cityflow-project/CityFlow#109]
I've finished with `sudo apt update && sudo apt install -y build-essential cmake` and `git clone https://github.com/cityflow-project/CityFlow.git`.
However, when executing `pip install .`, I failed and received the following error: 
```C
 /usr/lib/gcc/x86_64-linux-gnu/9/include-fixed/bits/statx.h:46:10: fatal error: bits/statx-generic.h: No such file or directory
     46 | #include <bits/statx-generic.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.

```
I am using Ubuntu 19.04 and gcc 9.2.1.

**Comment by X3nOph0N** [comment]
Since I haven’t met this question, I suggest you to update your gcc which might works. By the way，when facing those questions which are more related to complier，you should search it in google or stackoverflow. Searching official document is also a good idea，but asking others here is not.

**Comment by ClearloveWei** [comment]
Save your _harsh_ words. You are not the only one who know google. In fact, if you have any single try in google, you would find it a rather rare problem.
However, it has been solved and maybe I should close this issue.
