### ISSUE TITLE
How to use  "generate_json_from_grid.py"

### ISSUE THREAD

**Issue by LuckyLeeLL** [cityflow-project/CityFlow#111]
Dear develpoer:
       Can you specific explain how to use generate_json_from_grid？Beside, it can design different arrive rate？

**Comment by LuckyLeeLL** [comment]
When i use “generate_json_from_grid.py”


TypeError: gridToRoadnet() got an unexpected keyword argument 'intersections'

**Comment by zhc134** [comment]
Use `generate_grid_scenarios.py` instead. 
Please check `readme.md` which I just added in https://github.com/cityflow-project/CityFlow/tree/master/tools/generator

**Comment by LuckyLeeLL** [comment]
> Use `generate_grid_scenarios.py` instead.
> Please check `readme.md` which I just added in https://github.com/cityflow-project/CityFlow/tree/master/tools/generator

Can we set the arrival rate and the total travel time ?
