### ISSUE TITLE
parameter settings

### ISSUE THREAD

**Issue by zzws603** [cityflow-project/CityFlow#113]
Excuse me ，I am new to CityFlow. I wonder to know could CityfFlow set the following parameters, including ACTION__PATTERM, NUM_INTERSECTIONS, MIN_ACTOPM_TIME, YELLOW_TIME, ALL_RED_TIME, NUM_PHASES, NUM_LANES, ACTION_DIM, MEASURE_TIME. These parameters appear in PressLight.
Thanks in advance.

**Comment by only-changer** [comment]
In the Presslight paper, they conduct experiments on CityFlow. The parameters you mentioned in the issue are not the parameter of CityFlow but of their RL model.
