### ISSUE TITLE
How to install in GCP Console?

### ISSUE THREAD

**Issue by fxsatrio99** [cityflow-project/CityFlow#128]
I am new to GCP Console and new to this application project. I have pull the docker image and run it as the installation guide in Cloud Shell. But I don't know how to operate it. In the installation guide, use import CityFlow, but everytime I used "python3" in Cloud Shell and use import CityFlow, the command will say like this:

root@b63418639ad1:/# python3
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CityFlow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'CityFlow'

So I get confused. Please help me, I want to learn but it's too few for me to get the information from other source than the installation guide. Thank you in advance

**Comment by fxsatrio99** [comment]
I make JupyterLab on GCP Console and has installed CityFlow. When I want to run cityflow.Engine, the prompt says 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a0b957e36ed7> in <module>
----> 1 eng = CityFlow.Engine

AttributeError: module 'CityFlow' has no attribute 'Engine'

I don't know what to do from this. I checked the documentation and Engine is there. Any tips on this?

**Comment by zhc134** [comment]
Please check your python code, it should be `cityflow` rather than `CityFlow`
```
import cityflow
eng = cityflow.Engine(config_path, thread_num=1)
```
