### ISSUE TITLE
an issue about the threads_num

### ISSUE THREAD

**Issue by JinmingM** [cityflow-project/CityFlow#131]
Hello, I have a question when using CityFlow. After setting thread_num, for example:
self.eng = cityflow.Engine(cityflow_config, thread_num=thread_num)
I set thread_num=1,2,4,8,16, and then run 1e5 steps, why are they about the same time?
Looking forward to your reply.

**Comment by only-changer** [comment]
Hmmm, can you test a few more settings, I have not met something like this.

**Comment by zhc134** [comment]
Try running with larger road network
