### ISSUE TITLE
ModuleNotFoundError: No module named 'CityFlow'

### ISSUE THREAD

**Issue by zql1015** [cityflow-project/CityFlow#132]
I followed every step of the tutorial and succeeded,why ModuleNotFoundError: No module named 'CityFlow'

**Comment by zql1015** [comment]
> I followed every step of the tutorial and succeeded,why ModuleNotFoundError: No module named 'cityflow'

**Comment by only-changer** [comment]
Did you pip install Cityflow and use the same python for running code?

**Comment by Sheagu** [comment]
Same issue here. Have you solved it?

**Comment by Sheagu** [comment]
Every time you recreate a new Python environment, you should reinstall cityflow, using command `pip install .` as instructed. I just solved the issue in this way.
