### ISSUE TITLE
Grid Generation Error

### ISSUE THREAD

**Issue by AhmadM-DL** [cityflow-project/CityFlow#136]
I am trying to generate a grid roadnet of 1x8 dimensions ( eight consecutive intersections)
However executing the grid generator with params 1 and 8 is returning a grid of shape 1x2.
Any though?

**Comment by only-changer** [comment]
Emmm, I can't figure out why this happens. Could you please try to read the code of "generate_json_from_grid.py", which is a very simple and clear code.
