### ISSUE TITLE
Dynamic and manual control over vehicle speed/position

### ISSUE THREAD

**Issue by zlg9folira** [cityflow-project/CityFlow#140]
I am wondering if this simulator provides an interface to control position (x,y) and velocity for specific vehicle IDs on the fly and during simulation. Like, when you want to manually drive one or more vehicles at your desired location/speed. That is something supported by SUMO and other simulators, however, I was not able to find an answer in CityFlow documentation.

**Comment by zhc134** [comment]
CityFlow supports change vehicle speed on the fly, use `set_vehicle_speed` API, see [https://cityflow.readthedocs.io/en/latest/start.html#control-api](https://cityflow.readthedocs.io/en/latest/start.html#control-api)
