### ISSUE TITLE
Problems about converter.py

### ISSUE THREAD

**Issue by MFeng1221** [cityflow-project/CityFlow#144]
When converting the SUMO roadnet file into CityFlow roadnet format, both the example atlanta_sumo.net.xml and the file I got from SUMO, which generated from OpenStreetMap, cannot convert successfully, with following error:
![image](https://user-images.githubusercontent.com/34956215/142761842-9fa06c12-64c7-409d-85fd-2f52a0ee08d3.png)
How can I fix this problem?

**Comment by 16131zzzzzzzz** [comment]
https://github.com/cityflow-project/CityFlow/issues/107
