### ISSUE TITLE
drawing roadnet failed

### ISSUE THREAD

**Issue by La-Seine** [cityflow-project/CityFlow#147]
![image](https://user-images.githubusercontent.com/40331809/149702455-78873f92-c3c2-461f-a299-5a0939bb9e01.png)

**Comment by Fly-Pluche** [comment]
The same as you .Do you solve it?

**Comment by Siaaa-3** [comment]
I have the same problem. Have you solved?

**Comment by La-Seine** [comment]
no,I later used SUMO




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cityflow-project/CityFlow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月5日(星期天) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cityflow-project/CityFlow] drawing roadnet failed (Issue #147)





 
I have the same problem. Have you solved?

**Comment by Siaaa-3** [comment]
all right. But still thank you for reply to me~



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 6, 2022 09:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cityflow-project/CityFlow] drawing roadnet failed (Issue #147)




 no,I later used SUMO 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "cityflow-project/CityFlow"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年6月5日(星期天) 晚上7:01 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [cityflow-project/CityFlow] drawing roadnet failed (Issue #147) 
 
 
 
 
 
   
 I have the same problem. Have you solved?

**Comment by zhc134** [comment]
Please check if the roadnet file is the [replay roadnet file] generated by CityFlow, which is defined in `roadnetLogFile` in `config.json`.
