### ISSUE TITLE
Problem with loading the roadnetLogFile.json and replay.txt in the index.html

### ISSUE THREAD

**Issue by Zhenlin-Xu** [cityflow-project/CityFlow#154]
**Great work for MRL traffic simulator!**

I am currently trying to visualize the traffic simulation process. I firstly using the generated `roadnetLogFile`.json and `replay.txt` to replay in the browser. However, i think there is no reaction in the webpage. I am wondering what is wrong with the GUI part?

**Comment by Siaaa-3** [comment]
I have same problem! have you solve this problem?

**Comment by Zhenlin-Xu** [comment]
Yes. 

You should open these files by Firefox browser on Ubuntu. It doesn't work well on Windows. Maybe the whole project is developed on Linux (Ubuntu) platform so it is not compatible with Windows well enough.
