### ISSUE TITLE
What does 'flow_4_1_shadow' mean?

### ISSUE THREAD

**Issue by Sheagu** [cityflow-project/CityFlow#155]
I used the function `get_lane_vehicles()` and the dictionary returned includes a weird item 'flow_4_1_shadow':
![image](https://user-images.githubusercontent.com/54973652/161879782-f98e8c5b-cbff-4035-b1c3-d3585f93fe3e.png)
What does 'shadow' mean?

**Comment by zhc134** [comment]
`shadow` vehicle is related to lane changing mechanism, when a vehicle A is changing from lane 1 to lane 2, a shadow of vehicle A will be inserted to lane 2 and removed after completion of lane changing.
