### ISSUE TITLE
A kind of tutorial for beginners

### ISSUE THREAD

**Issue by EvanMath** [cityflow-project/CityFlow#156]
Hey guys,

I would like to ask if there are any tutorials for Windows users. I have used the docker but I don't know how to proceed further after that step. Is it possible to build a simple guide of bullets on what to do? I want to cityflow for my thesis so any help would be great.

Regards.

**Comment by tobiasjpark** [comment]
I second this, I'm trying to use this for a school project but I have no idea how to launch the GUI and the documentation doesn't even mention it at all! This is being marketed as being better than SUMO but SUMO was easy to install and launch so that has not been my experience so far.

**Comment by EvanMath** [comment]
@tobiasjpark I have written a short guide on how to install Cityflow in WSL2 (https://medium.com/@EvanMath/how-to-install-the-cityflow-simulator-in-windows-11-a89ef4ea2397). I hope that helps.

**Comment by TrinhTuanHung2021** [comment]
> @tobiasjpark I have written a short guide on how to install Cityflow in WSL2 (https://medium.com/@EvanMath/how-to-install-the-cityflow-simulator-in-windows-11-a89ef4ea2397). I hope that helps.

Hello. I have just installed CityFlow. But I did not see the GUI when running models. So could you tell me how to show GUI?

**Comment by EvanMath** [comment]
> 

Not sure how to help here. I picked SUMO finally. But [here](https://traffic-signal-control.github.io/#open-datasets) you can find more info related to cityflow.

**Comment by TrinhTuanHung2021** [comment]
> > Hello. I have just installed CityFlow. But I did not see the GUI when running models. So could you tell me how to show GUI?
> 
> Not sure how to help here. I picked SUMO finally. But [here](https://traffic-signal-control.github.io/#open-datasets) you can find more info related to Cityflow.

I saw the instructions to run GUI
![image](https://user-images.githubusercontent.com/82990411/192143932-f0982f02-2b14-4dad-ac69-173e77515c83.png)

But it was too complicated, so finally I chose Sumo to simulate
