### ISSUE TITLE
Does cityflow have gui ?

### ISSUE THREAD

**Issue by Siaaa-3** [cityflow-project/CityFlow#158]
I wanna know whether the cityflow has gui? Just like sumo-gui, so that we can create a roadnet like drawing a line.

Or cityflow can only create these roadnet/flow files by write the json file ?

**Comment by TrinhTuanHung2021** [comment]
> I wanna know whether the cityflow has gui? Just like sumo-gui, so that we can create a roadnet like drawing a line.
> 
> Or cityflow can only create these roadnet/flow files by write the json file ?

![image](https://user-images.githubusercontent.com/82990411/192106033-5e7a4a42-8db8-4ff3-b6ce-16947f4a567f.png)
https://cityflow.readthedocs.io/en/latest/replay.html#start

**Comment by TrinhTuanHung2021** [comment]
But I do not understand to choose files in the model.  Compared to Sumo, It is complicated and time-consuming
