### ISSUE TITLE
how to use frap-pub or metalight output on cityflow's index.html

### ISSUE THREAD

**Issue by nimasler** [cityflow-project/CityFlow#159]
![螢幕擷取畫面 2022-11-12 174924](https://user-images.githubusercontent.com/118043395/201469016-df2e9a52-b10f-43af-9fbf-8c5db4b07096.png)
![螢幕擷取畫面 2022-11-12 174940](https://user-images.githubusercontent.com/118043395/201469020-8fc3b787-33e6-41a4-9aa9-dd814614071d.png)

這是因為資料格式不一樣嗎

**Comment by zhc134** [comment]
You should use the `roadnetLogFile` generated by CityFlow, as specified in config

**Comment by nimasler** [comment]
![螢幕擷取畫面 2022-11-12 174924](https://user-images.githubusercontent.com/118043395/201475827-eeffbb6b-d232-406b-a584-dcc06c3caaaf.png)
![image](https://user-images.githubusercontent.com/118043395/201475830-1dc573fa-30a5-4196-bfad-1483ee5dea05.png)
![螢幕擷取畫面 2022-11-12 174940](https://user-images.githubusercontent.com/118043395/201475851-88082738-88c8-471c-a2cc-2218a335bf48.png)

do you mean to use the frap-pub input and  do again this step

**Comment by nimasler** [comment]
![螢幕擷取畫面 2022-11-12 174924](https://user-images.githubusercontent.com/118043395/201475880-85fda0bd-b2e6-4358-a96a-eafcb890a9d2.png)
![螢幕擷取畫面 2022-11-12 174940](https://user-images.githubusercontent.com/118043395/201475888-5831f160-82b7-45d2-a8cf-043306e91087.png)

do you mean to use the frap-pub's input and  do again this step

**Comment by zhc134** [comment]
the roadnet json file starting with `intersections` corresponds to `roadnetFile` in config, which is the input of CityFlow

the roadnet json file starting with `static` corresponds to `roadnetLogFile` in config, which is the output of CityFlow and is used in the Web GUI.

**Comment by nimasler** [comment]
ok thanks
