### ISSUE TITLE
cityflow for irregular Intersection 

### ISSUE THREAD

**Issue by WaterFountain-Jack** [cityflow-project/CityFlow#160]
Hi, with the help of the CityFlow you wrote, I've been able to run some regular road networks, but I'm having some problems with things like five-fork or three-fork where I can't code Intersection by rules (Many operations of cityflow are generated according to the fixed position of Intersection on the grid), is there a possibility that cityflow can expand and irregular Intersection?

**Comment by zhc134** [comment]
CityFlow support irregular intersections, you need to generate your own roadnet file as long as it conform to the format specified [here](https://cityflow.readthedocs.io/en/latest/roadnet.html)

**Comment by WaterFountain-Jack** [comment]
你好，我是宣传部的乔嗣尧，已收到您的来信，我会及时查收并回复。如果您有急事，请联系我： 19823327107  或   18087037706

**Comment by BackMountainDevil** [comment]
solution:

1. write irregular Intersection by hands
2. convert an irregular SUMO intersection into CityFlow format

CityFlow/tools/generate_grid_scenario.py can generate NxM grid road network with traffic flows(regular 4-fork). 

I guess he/she wants to knoe is there a tool to generate irregular Intersection roadnet

**Comment by WaterFountain-Jack** [comment]
你好，我是宣传部的乔嗣尧，已收到您的来信，我会及时查收并回复。如果您有急事，请联系我： 19823327107  或   18087037706
