### ISSUE TITLE
Error occurred when drawing

### ISSUE THREAD

**Issue by ygdl0228** [cityflow-project/CityFlow#161]
Traffic light shows white and replay doesn't show cars. 

![image](https://user-images.githubusercontent.com/65707601/204134446-075bb8b6-2e99-4be9-9b9c-83d5ca7364ac.png)
![image](https://user-images.githubusercontent.com/65707601/204134558-f332e632-b6e6-4a00-9f83-9a866eaf0075.png)

**Comment by ygdl0228** [comment]
![image](https://user-images.githubusercontent.com/65707601/204134355-910d116d-4cdd-4396-9b00-8786d1a0db44.png)

**Comment by zhc134** [comment]
Please check if the `replay.txt` and `replay_roadnet.json` corresponds to each other.

**Comment by ygdl0228** [comment]
These two documents are of course corresponding，Is it because replay.txt is too big

**Comment by ygdl0228** [comment]
of course
![image](https://user-images.githubusercontent.com/65707601/211322108-edaca7b5-dbf8-452d-bbc2-fa75d5d85122.png)
![image](https://user-images.githubusercontent.com/65707601/211322162-64c45400-0915-428d-aeec-bce0c85df42b.png)

**Comment by zhc134** [comment]
Please check the console tab in F12 tool, notice that you should open the console tab before you select replay file and start simulation.

**Comment by ygdl0228** [comment]
Sorry, I don't understand what you mean. I'm not very familiar with this place. I can open the console tab before I select replay file and start simulation. But there is nothing here
![image](https://user-images.githubusercontent.com/65707601/211325611-8e60b528-b7a6-43b2-ace4-495d8359ac3b.png)

**Comment by ygdl0228** [comment]
Is this what you need
![image](https://user-images.githubusercontent.com/65707601/211441193-df712498-763a-473f-9a6b-3bdbf9b202b1.png)

**Comment by zhc134** [comment]
Yes, there should be erros in the console. Could you please share the two replay files, so I can check them locally.

**Comment by ygdl0228** [comment]
ok, by email?

**Comment by zhc134** [comment]
You could upload them to a netdisc

**Comment by ygdl0228** [comment]
链接：https://pan.baidu.com/s/1jIlrzbDYTHd1mu2p3d9Qtg?pwd=p8bk 
提取码：p8bk

**Comment by Siaaa-3** [comment]
hi, I'm trying to use the simulator, but I get this page:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/71689053/236615557-05440362-8461-4288-9d46-645772f4e4b7.png">

Can you tell me what browser you use? and do you use Linux or Windows?

**Comment by BackMountainDevil** [comment]
> trying to use the simulator, but I get this

firefox on linux works too

**Comment by BackMountainDevil** [comment]
I have replayLog_fake.txt( 5.2 GiB)  and roadnetLog_fake.json( 1 MiB). Presee start will got "- Loading replayLog_fake.txtfailed" in Info Box.  I tried this at least three times bug got same result

I tried print the err info(frontend/script.js L125) in F12-console, and got 

```
error { target: FileReader, isTrusted: true, lengthComputable: true, loaded: 4294959104, total: 5555716025, srcElement: FileReader, currentTarget: FileReader, eventPhase: 2, bubbles: false, cancelable: false, … }
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: FileReader { readyState: 2, result: null, error: DOMException, … }
​
isTrusted: true
​
lengthComputable: true
​
loaded: 4294959104
​
originalTarget: FileReader { readyState: 2, result: null, error: DOMException, … }
​
returnValue: true
​
srcElement: FileReader { readyState: 2, result: null, error: DOMException, … }
​
target: FileReader { readyState: 2, result: null, error: DOMException, … }
​
timeStamp: 188629
​
total: 5555716025
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: ProgressEventPrototype { lengthComputable: Getter, loaded: Getter, total: Getter, … }
script.js:126:17
```

too big to render too?
