### ISSUE TITLE
How to run the manhattan data？

### ISSUE THREAD

**Issue by WaterFountain-Jack** [cityflow-project/CityFlow#162]
Please ask whether the manhattan data in the project MPLight is built based on cityflow, 
and whether there is a docker file similar to colight in the project MPLight？
Thank you very much!

**Comment by zhc134** [comment]
Please check [this repo](https://github.com/Chacha-Chen/MPLight/tree/master/data/manhattan)

**Comment by WaterFountain-Jack** [comment]
你好，我是宣传部的乔嗣尧，已收到您的来信，我会及时查收并回复。如果您有急事，请联系我： 19823327107  或   18087037706
