### ISSUE TITLE
How to use Simulator?

### ISSUE THREAD

**Issue by Siaaa-3** [cityflow-project/CityFlow#169]
I am trying to use Simulator.
I pulled this “cityflow-projecy/Cityflow” repository ，and have tried:
(1) directly oepn frontend/index.html with firefox(downloaded in my windows11)  broser
(2) pull a linuxserver/firefox by docker, and open index.html with this firefox(linux version)
but both the results are like following picture: can not show the simulated roads and vehicles, but can upload roadnetLogFile and flowLogFile.

What's wrong with my process?
How can I get the correct Simulator page? (or what broswer should I use?)
Please help me, thanks!

![image](https://user-images.githubusercontent.com/71689053/236615906-3339609d-223c-44bd-b5f1-075e4623c462.png)

**Comment by Siaaa-3** [comment]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/71689053/236628125-806a783a-f3fe-41c0-9234-4ee7766fb811.png">

**Comment by Siaaa-3** [comment]
the index.html page I opened is in this folder

<img width="474" alt="image" src="https://user-images.githubusercontent.com/71689053/236628198-0893c84d-4661-4320-9b1d-579d1a35107a.png">

**Comment by zhc134** [comment]
please use Chrome browser and see if it works

**Comment by Siaaa-3** [comment]
thanks, Chrome is ok
