### ISSUE TITLE
Segmentation fault when I try to use a roadnet from SUMO

### ISSUE THREAD

**Issue by josemanuelsannav** [cityflow-project/CityFlow#181]
I'm trying to use a roadnet converted from a SUMO roadnet of a real town (using openstreetmap ) . 
First y save the SUMO archive to a .net.xml. 
Then I convert it to a .json using the converter.py 
Finally I create the flow.json and try to use them .

**import cityflow
eng = cityflow.Engine("config.json")
Segmentation fault**

**Comment by TQX177** [comment]
have you solved the problem? I have the same issue

**Comment by josemanuelsannav** [comment]
sry , i don't remember, but I think that it depends of the shape of the roadnet or something. Try to create a 2x2 roadnet using cityflow instead of SUMO. If  it works is a problem in the process of transforming SUMO to cityflow and loading it into the  project.
