### ISSUE TITLE
It's in replay but no images are showing

### ISSUE THREAD

**Issue by TQX177** [cityflow-project/CityFlow#183]
![image](https://github.com/cityflow-project/CityFlow/assets/85486679/a38c00b4-b7b3-4282-bdb7-d30ff7713e8a)
Has anyone else encountered this error? How did you resolve it? I hope you can let me know, thanks!

**Comment by sunxiaoyu12** [comment]
I have the same problem with yuo,have you solved it?

**Comment by sunxiaoyu12** [comment]
> ![image](https://private-user-images.githubusercontent.com/85486679/318329314-a38c00b4-b7b3-4282-bdb7-d30ff7713e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYzMTUsIm5iZiI6MTcxMjgwNjAxNSwicGF0aCI6Ii84NTQ4NjY3OS8zMTgzMjkzMTQtYTM4YzAwYjQtYjdiMy00MjgyLWJkYjctZDMwZmY3NzEzZThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAzMjY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNzE1YWQxNDVlOWMxYzdlMTBkNDM1OWVlMTQyNmNmZGQ1N2ZjMDI0OWZjYTNjODQ0NjQyYjI0NmNlZDIzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XImrMPn1DIqxEra4d6LOPIa6z6LaOofhgoe2XxZyvzY) Has anyone else encountered this error? How did you resolve it? I hope you can let me know, thanks!

I have the same problem with yuo,have you solved it?

**Comment by TQX177** [comment]
> > ![image](https://private-user-images.githubusercontent.com/85486679/318329314-a38c00b4-b7b3-4282-bdb7-d30ff7713e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYzMTUsIm5iZiI6MTcxMjgwNjAxNSwicGF0aCI6Ii84NTQ4NjY3OS8zMTgzMjkzMTQtYTM4YzAwYjQtYjdiMy00MjgyLWJkYjctZDMwZmY3NzEzZThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAzMjY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNzE1YWQxNDVlOWMxYzdlMTBkNDM1OWVlMTQyNmNmZGQ1N2ZjMDI0OWZjYTNjODQ0NjQyYjI0NmNlZDIzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XImrMPn1DIqxEra4d6LOPIa6z6LaOofhgoe2XxZyvzY) Has anyone else encountered this error? How did you resolve it? I hope you can let me know, thanks!
> 
> I have the same problem with yuo,have you solved it?

Yes I solved it, open the console with F12 when displaying the page in the browser I had a rendered template on my side that wouldn't load, I configured it manually and it showed up!
