### ISSUE TITLE
Can I get the code that generates frontend/replat.txt and frontend/roadnet.json?

### ISSUE THREAD

**Issue by mjm212** [cityflow-project/CityFlow#2]
I'm very thanks for you about you create a new traffic simulator CityFlow with fundamentally optimized data structures and efficient algorithms. I'm very interesting in this learning platform. But I think the CityFlow's usage introduction is too simple. And I hope I can get the code that generates frontend/replat.txt and frontend/roadnet.json. Thank you for you help.

**Comment by zhc134** [comment]
Hi mjm212, thanks for your interest! We will improve the documentation before August.

For now, as shown in [Quick Start Guide](https://cityflow.readthedocs.io/en/latest/start.html)
You can generate grid roadnet and flow files using `tools/generate_grid_scenario.py`
For example, you can generate a 2x3 roadnet with predefined traffic light plan and a corresponding flow file with
`python generate_grid_scenario 2 3 --roadnetFile roadnet.json --flowFile flow.json --dir . --tlPlan`

**Comment by mjm212** [comment]
Thanks for your help!

**Comment by anishsetya** [comment]
How can i generate a senario using an existing roadnet.json file.
