### ISSUE TITLE
Adding Cityflow module to gym

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#23]
I am working on a small repository that adds Cityflow to OpenAI's `gym` RL library, and I am planning on open-sourcing it soon. I am starting with a very simple and minimal setting, and am hoping to expand it down the road. One of the reasons I want to open-source it is Cityflow is an amazing library leaps a head of SUMO, and yet not as many people are aware of it. By adding it to one of the most popular RL libraries, I am hoping more people would get easier access to Cityflow.

Would you guys be willing to help with this repository? I would really appreciate any feedback or contributions.

Thanks

**Comment by zhc134** [comment]
@ThisIsIsaac 

Thanks a lot for your comments and interest! We really appreciate it.

Just to make it clear, by "adds Cityflow to OpenAI's `gym` RL library", do you mean implementing a gym-compatible Env (implement step(), reset(), etc.) and open source it as a separate repo? If so, actually we are working on it recently, we plan to publish a repo just like `openai/multiagent-particle-envs`. which is a multi-agent Env with some predefined scenarios. In our case, we will provide several predefined roadnet and flow settings, as well as some state and reward calculation funtions. Also, we will provide baseline algorithms including traditional TSC methods and RL-based TSC methods.

**Comment by ThisIsIsaac** [comment]
> Just to make it clear, by "adds Cityflow to OpenAI's gym RL library", do you mean implementing a gym-compatible Env (implement step(), reset(), etc.) and open source it as a separate repo?

yes

> If so, actually we are working on it recently, we plan to publish a repo just like openai/multiagent-particle-envs

Wow, that is great to hear! When are you planning on releasing the environments and the models?

**Comment by zhc134** [comment]
@ThisIsIsaac 
Next week, stay tuned :smiley:

**Comment by zhc134** [comment]
please check https://github.com/zhc134/tlc-baselines
