### ISSUE TITLE
set replay file path with Python API

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#29]
## Feature

The ability to set what file to wrtie the replays to in python runtime using Python API

## Why useful

It is common to run hundreds or thousands of episodes. Sometimes we want to look at a specific episode for debugging purposes. Currently, older replays are either overwritten or newer replays are appended to the older replay files. This makes it difficult (impossible in the case older replays are overwritten) to navigate through hundreds of episodes. 

## How it will be used

```python

while current_episode < total_episodes:
    cityflow.set_replay_path(str(current_episode) + ".txt")) # new API to be added
    # start cityflow
```

**Comment by zhc134** [comment]
@ThisIsIsaac 

please check #31 and feel free to leave any comments!

**Comment by ThisIsIsaac** [comment]
Thanks! I will give it a try and get back to you :)

**Comment by ThisIsIsaac** [comment]
Closing as this has been implemented.
