### ISSUE TITLE
Feature request: Python API to set random seed

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#32]
RL often requires  using tens or hundreds of different random seeds to validate the performance of an agent. A python API to set random seed would be extremely helpful.

**Comment by ThisIsIsaac** [comment]
ping!

**Comment by zhc134** [comment]
Sorry for the replay, check #34

**Comment by ThisIsIsaac** [comment]
Great! looking forward to it!
