### ISSUE TITLE
can't view saved replay

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#35]
## works on demo replay

viewing sample replay files: `replay.txt` and `roadnet.json` that you can download with `download_replay.py` works fine. When I turn on `app.py` and go to this address:

`http://localhost:8080/?roadnetFile=roadnet.json&logFile=replay.txt`

The replay is displayed fine.

## Doesn't work for my replay

However, if I try to view my custom replay files (`ep_9.txt` and `roadnet.json`) that I have saved under `/home/isaac/CityFlow/frontend/replay/debug` with this URL:

`http://localhost:8080/?roadnetFile=debug/roadnet.json&logFile=debug/ep_9.txt`

the browser hangs.

<img width="2011" alt="Screen Shot 2019-09-06 at 17 18 45 PM" src="https://user-images.githubusercontent.com/49523965/64412490-6bad4700-d0ca-11e9-9369-ec8874f43127.png">

here is the output of `python app.py`:

```
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Sep/2019 17:09:46] "GET /?roadnetFile=roadnet.json&logFile=replay.txt HTTP/1.1" 200 -
127.0.0.1 - - [06/Sep/2019 17:10:43] "GET /?roadnetFile=debug/roadnet.json&logFile=debug/ep_9.txt HTTP/1.1" 200 -
```

## my replay files

[replay.zip](https://github.com/cityflow-project/CityFlow/files/3582951/replay.zip)

**Comment by zhc134** [comment]
could you please check the browser's console?

**Comment by soodoshll** [comment]
And there is another problem: the "roadnet.json" should be the "roadnetLogFile" you assigned in the config.json file, instead of the roadnet config file (I admit it's a little bit confusing)

**Comment by ThisIsIsaac** [comment]
@soodoshll 

> the "roadnet.json" should be the "roadnetLogFile" you assigned in the config.json file, instead of the roadnet config file

I've been using `roadnet.json` instead of `roadnetlog.json`. Works for me now. Thanks!
