### ISSUE TITLE
Feature request: changing replay saving & playing path

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#39]
1. currently, replay files must be inside `CityFlow/frontend/replay`. This necessitates copying files from a different directory every time I want to see a replay. Being able to play a replay file in any directory would be very helpful.

2. Currently, replay files have to be saved to a path related to `dir` in `config.json`. However, this may not be an ideal setup. Often, environment-specific files such as `config.json` want to be saved in a completely unrelated path to log / replay files. Being able to save replay files using `set_replay_file` API to a path that is unrelated to `dir` in `config.json` would be helpful.

**Comment by zhc134** [comment]
1. in PR #45 , we enable users to select replay and roadnet.
2. set_replay_file does not influence roadnet.json but only replay.txt, since `roadnet.json` is related to `dir`, it would be a little bit strange if `replay.txt` does not. we will give it a careful reconsideration
