### ISSUE TITLE
Errors raised in loading roadnet file

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#44]
I get errors on loading `roadnet.json` file. The strange thing is I have made no modifications to: `config.json`, `roadnet.json`, and `flow.json` or their paths. I have made sure of this by comparing git history. And the same setup worked just fine.

## directory structure

```
1x1_config/
        config.json
        flow.json
        roadnet.json
```

If I run the blow python command **inside `1x1_config`**:

```python
>>> import cityflow
>>> eng = cityflow.Engine("config.json")
```

I get below error message:

```
roadnet: expected type object
load config failed!
```

---

## cannot load built-in example `config.json`

I was able to reproduce the error with the builtin [examples](https://github.com/cityflow-project/CityFlow/tree/master/examples). Under the `examples` directory, I started `python` interpreter and typed:

```python
>>> import cityflow
>>> eng = cityflow.Engine("config.json")
```

and got error:

```
cannot open roadnet file
loading roadnet file error!
load config failed!
```

**Comment by zhc134** [comment]
currently all path is related to `dir`, so when using builtin examples, you should run under the parent folder of `examples`

**Comment by ThisIsIsaac** [comment]
> currently all path is related to dir, so when using builtin examples, you should run under the parent folder of examples

thanks!
