### ISSUE TITLE
能否支持Windows pip安装

### ISSUE THREAD

**Issue by zzcNEU** [cityflow-project/CityFlow#5]
你好，我不会Docker,ubuntu，请问你们支持Windows安装吗？

**Comment by Hzfengsy** [comment]
Thank you for your interest. For now CityFlow should works well on Windows for we have only use native C++ without specific system call. Unfortunately, we have not do any test or experiment on Windows platform and won't do that in the near future. We would appreciate it If you are willing to help us test CityFlow on Windows and try to fix any potential problems. If you are only try to use CityFlow, we recommend you to use WSL (Windows Subsystem for Linux) or docker. Both are not difficult to learn. I believe you can get it.
