### ISSUE TITLE
Unexpected roadnet rendering

### ISSUE THREAD

**Issue by Fullstop000** [cityflow-project/CityFlow#62]
I generated a raw `roadnet.json` with some `roadLink`s like below: 
```
     {
          "type": "turn_left",
          "startRoad": "edge-1",
          "endRoad": "edge-10",
          "laneLinks": [
            {
              "startLaneIndex": 0,
              "endLaneIndex": 0,
              "points": [
                {
                  "x": 960,
                  "y": 390
                },
                {
                  "x": 978.6,
                  "y": 392.52
                },
                {
                  "x": 996.98,
                  "y": 399.63
                },
                {
                  "x": 1014.6,
                  "y": 410.62
                },
                {
                  "x": 1030.94,
                  "y": 424.8
                },
                {
                  "x": 1045.45,
                  "y": 441.46
                },
                {
                  "x": 1057.62,
                  "y": 459.91
                },
                {
                  "x": 1066.91,
                  "y": 479.44
                },
                {
                  "x": 1072.78,
                  "y": 499.36
                },
                {
                  "x": 1074.71,
                  "y": 518.97
                },
                {
                  "x": 1072.17,
                  "y": 537.57
                }
              ]
            }
          ]
        },
```

As posted, the lane link is organized by some points which should be performed like a real curve. But I got weird intersections without any internal lane link displaying:
![image](https://user-images.githubusercontent.com/12471960/66799317-2c80da00-ef43-11e9-9b14-33f0ab89bfc1.png)

Does the frontend tool support this feature?

**Comment by soodoshll** [comment]
Hi. 

I guess the problem is caused by "width". Did you set the "width" property of the intersection? This represents the size of the intersection. If it is set to 0, the endpoints of the roads will overlap. It is recommended to set width to a large enough value so that the roads do not overlap.

And lanelinks won't be displayed explicitly. Vehicles which have entered an intersetion will run along the lanelink but it won't be displayed as a line or curve.

**Comment by Fullstop000** [comment]
Thank you for your help. @soodoshll

**Comment by LiiangZhang** [comment]
I have some questions, How the road figure was rendered, I can not get the commands that can render the rodent.json. Could you answer this problem? Thank you very much.

**Comment by soodoshll** [comment]
> I have some questions, How the road figure was rendered, I can not get the commands that can render the rodent.json. Could you answer this problem? Thank you very much.

If you already have roadnet.json, you can use this roadnet file to run a simulation and it will generate a replay file (maybe roadnet_replay.json) and you can use web browser to open `frontend/index.html` to replay it. For this part, please refer to docs about how to run a simulation. If you don't have the vehicle flow configuration, you can use a empty file.
