### ISSUE TITLE
running SUMO simulation

### ISSUE THREAD

**Issue by Viole-Grace** [cityflow-project/CityFlow#67]
Is there a way to take a SUMO simulation file and generate a cityflow json for the same? I want to overlay it with real world maps and traffic simulations. Any idea how to get around it?

**Comment by only-changer** [comment]
Yes, there is. 
Use /tools/converter/converter.py, which will convert *.net.xml to *.json.
By the way, there is a nosm2cityflow converter in the pull request, which will directly convert osm roadnet to cityflow roadnet.

**Comment by LuckyLeeLL** [comment]
> Yes, there is.
> Use /tools/converter/converter.py, which will convert *.net.xml to *.json.
> By the way, there is a nosm2cityflow converter in the pull request, which will directly convert osm roadnet to cityflow roadnet.


Excuse me, i want ask one question about sumo. 
The data of city flow can apply into sumo.

**Comment by zhc134** [comment]
please check the converter https://github.com/cityflow-project/CityFlow/tree/master/tools/converter

**Comment by eddymarts** [comment]
I read there were some errors for simulations from osm files converted directly into cityflow. Are those fixed?

**Comment by iuu-zyh** [comment]
I'm sorry,there is wrong that TypeError: cannot unpack non-iterable Phase object,but I just used the example.
