### ISSUE TITLE
how to obtain the single vehicle' waiting time and accumulated waiting time?

### ISSUE THREAD

**Issue by XiaoWangya** [cityflow-project/CityFlow#68]
I don't find any API.

**Comment by XiaoWangya** [comment]
This is done via a simple logic, but how to obtain the current signal phase?

**Comment by only-changer** [comment]
Sorry about that. We will try to add the API as soon as possible. Could you please specifically describe what you need?

**Comment by XiaoWangya** [comment]
> Sorry about that. We will try to add the API as soon as possible. Could you please specifically describe what you need?

I'd like to know how to get the current signal phase, I wish there is a function, input the id of the intersection and output its current signal phase (like 1 or 0)

**Comment by only-changer** [comment]
> > Sorry about that. We will try to add the API as soon as possible. Could you please specifically describe what you need?
> 
> I'd like to know how to get the current signal phase, I wish there is a function, input the id of the intersection and output its current signal phase (like 1 or 0)

I‘m sorry that for now, we don't have that API. But, since the signal plan is set by yourself, you can directly get the current signal phase without running cityflow.

**Comment by Zhikaiiii** [comment]
> This is done via a simple logic, but how to obtain the current signal phase?

hey! I wonder how do you get the the single vehicle' waiting time and accumulated waiting time?thanks

**Comment by Sheagu** [comment]
Same question!!!
