### ISSUE TITLE
How do I change the route of a vehicle during simulation?

### ISSUE THREAD

**Issue by TTyka** [cityflow-project/CityFlow#72]
Who can help me! Because of the traffic jam, I want to change the route of the vehicles about to enter the simulation road, so as to ease/reduce traffic jams. I didn't find a python API that can change the vehicle path. I found lanechange.cpp and lanechange.h in the SRC folder but I'm not sure if the functions in them can change the vehicle path during simulating.

**Comment by soodoshll** [comment]
I'm sorry that for now routing is still static and can't be interfered once the vehicle has set off.

**Comment by TTyka** [comment]
Thanks a lot for your reply.
