### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by IridescentL** [cityflow-project/CityFlow#73]
I use cityflow to simulate a 2*2 road net in macOS, when its step reaches around 500, it turns out the memory usage of the python program is more than 2GB. Is this a normal case or my personal issue that the simulator consumes this much memory?

**Comment by Hzfengsy** [comment]
I think it is not a normal case unless you have put hundreds of thousands of cars on the road.

**Comment by IridescentL** [comment]
There are about three hundred cars on the road, and I bet many cars are in the road waiting buffer so they do not come out yet due to heavy traffic jam. When I use the reset interface to clear the road a few times, program memroy usage continues increasing, far beyond my computer's memroy limit.

**Comment by Hzfengsy** [comment]
We have tested on large scenarios of more than 10,000 cars on the road. I think it is because you have stored too much data in python. Do you store the history information of cars? You can try to run CityFlow without the RL algorithm and any other observation.
