### ISSUE TITLE
loading road net and flow configuration 

### ISSUE THREAD

**Issue by qmlzhk** [cityflow-project/CityFlow#74]
Is there any other ways to load a road net or flow configuration rather than through predefining them in the configuration file? For example, load some road net, load one flow file, run it, then load another flow file, run it, etc... 
Thanks!

**Comment by soodoshll** [comment]
My suggestion is to use json module of python to generate a json file dynamically. When you need a new configuration, write it to a temporary config file. Then delete the old engine object and create a new one with the new config file.

**Comment by qmlzhk** [comment]
I find that this simulator provides an interface to get average travel time. How does the system calculate it?
Thanks!

**Comment by soodoshll** [comment]
Please refer to  https://traffic-signal-control.github.io/TSCC2019/evaluation.html
