### ISSUE TITLE
The generated replayLogFile does not show vehicles in the replay simulator

### ISSUE THREAD

**Issue by SamuelXie** [cityflow-project/CityFlow#78]
I run an easy demo to generate replay files, 'roadnet.json', 'flow.json', 'config.json' are same as the files below in  'example' folder.
The demo code are shown as follows：
```
import cityflow

eng = cityflow.Engine('examples/config.json')

for i in range(500):
    eng.next_step()
```
I can get roadnetLogFile and replayLogFile, and the road, number of vehicles, current step are shown correctly. 
However, vehicles are invisible in the replay simulator.
So, how to make vehicles display normally during the replay process?

**Comment by zhc134** [comment]
Could you please check the infobox in UI, is it same as mine?
If so, please check console of browser and see if there are any warnings or errors.
![image](https://user-images.githubusercontent.com/44251346/76101943-30a0b780-600a-11ea-8a55-841461d000f5.png)

**Comment by SamuelXie** [comment]
Thank you for your rapidly reply.
I change a computer to run the same code, it works correctly.
This may be caused by the cityflow version in my docker container not latest.
Thanks a lot!

**Comment by MPHarryZhang** [comment]
> 你能检查一下 UI 中的信息框，它和我的一样吗？ 如果是这样，请检查浏览器的控制台，看看是否有任何警告或错误。 ![图片](https://user-images.githubusercontent.com/44251346/76101943-30a0b780-600a-11ea-8a55-841461d000f5.png)

您好，我也遇到了这个问题，得到roadnetLogFile和replayLogFile，并且正确显示了道路，车辆数量，当前步骤，但是，一样车辆在回放中不显示，我检查了一下页面，与您的一致，在谷歌浏览器中只爆出一个警告：DevTools failed to load source map: Could not load content for file:///D:/Harry/WangZhiwen/CityFlow-master/CityFlow-master/frontend/pixi.min.js.map: System error: net::ERR_FILE_NOT_FOUND，在此之前，我已将该js下载到本地并修改了html中script引用路径，否则浏览器将爆出net::ERR_FILE_NOT_FOUND 的error，希望得到您的指点，可能有哪些原因导致车辆不显示？

**Comment by MPHarryZhang** [comment]
> 你能检查一下 UI 中的信息框，它和我的一样吗？ 如果是这样，请检查浏览器的控制台，看看是否有任何警告或错误。 ![图片](https://user-images.githubusercontent.com/44251346/76101943-30a0b780-600a-11ea-8a55-841461d000f5.png)

您好，我遇到生成的重播文件中，缺少车辆len和width两个值，导致重播不显示车辆，但是，cityflow里面是有的，我不知道是如何导致的问题，怎么解决他？
