### ISSUE TITLE
Simple main cpp demo

### ISSUE THREAD

**Issue by yumianhuli2** [cityflow-project/CityFlow#79]
May your team provide a simplest running example of a pure C++ main.cpp?Thank you!

**Comment by soodoshll** [comment]
please refer to [simple_run.cpp](https://github.com/cityflow-project/CityFlow/blob/master/tools/debug/simple_run.cpp).

an environment variable `DATADIR` is necessary for running.

**Comment by yumianhuli2** [comment]
> please refer to [simple_run.cpp](https://github.com/cityflow-project/CityFlow/blob/master/tools/debug/simple_run.cpp).
> 
> an environment variable `DATADIR` is necessary for running.
Ok,I just found simple_run.cpp,But may you explain in detail how to use this CPP file？
And I do not know how to set an environment variable DATADIR.
I really appreciate for your help！！

**Comment by soodoshll** [comment]
Here is an example of how to run this C++ file. (following commands are run under CityFlow directory)

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
cd ../
DATADIR=./examples/ ./build/tools/debug/simple_run  --configFile config.json
```

**Comment by yumianhuli2** [comment]
> Here is an example of how to run this C++ file. (following commands are run under CityFlow directory)
> 
> ```
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Debug ..
> cd ../
> DATADIR=./examples/ ./build/tools/debug/simple_run  --configFile config.json
> ```


Hello! I followed your steps and got bash: ./build/tools/debug/simple_run: No such file or directory.
cmake process is ok but there was no simple_run file built?

**Comment by soodoshll** [comment]
> > Here is an example of how to run this C++ file. (following commands are run under CityFlow directory)
> > ```
> > mkdir build
> > cd build
> > cmake -DCMAKE_BUILD_TYPE=Debug ..
> > cd ../
> > DATADIR=./examples/ ./build/tools/debug/simple_run  --configFile config.json
> > ```
> 
> Hello! I followed your steps and got bash: ./build/tools/debug/simple_run: No such file or directory.
> cmake process is ok but there was no simple_run file built?

Sorry, I made a mistake. there should be a `make` after the cmake command.
