### ISSUE TITLE
Error in non-Grid intersection

### ISSUE THREAD

**Issue by oroojlooy** [cityflow-project/CityFlow#81]
Hi, 

When I use grid intersections I am able to create an instance of cityflow environment and everything works fine. But, when I switch to non-grid environment, I have some issues.

I built a non-grid intersection `road-net` and `traffic-flow` file, including one intersection with three roads, and tried to build an instance of the CityFlow environment by them, but faced a `segmentation fault` error. I tried both CityFlow environment and the engine.so through the `anon_env.py` from `https://traffic-signal-control.github.io/`. When I call it directly by `CityFlow`, I simply run:
`eng = cityflow.Engine(config_file=config_file_, thread_num=1)
` 
, which results in:
`Segmentation fault
`

When, I run it by `anon_env`, the error is a bit more informative:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
`
which happens when I call the `eng.load_roadnet` function from engine. 
I ran this procedure by using the `anon_env` with the `engine.so` which I downloaded from [here](https://github.com/gjzheng93/frap-pub/blob/master/engine.cpython-36m-x86_64-linux-gnu.so).
I attached my `road-net` and `traffic-flow` files, which I changed them as `txt` file since github does not allow `json` files. 
[traffic_flow.txt](https://github.com/cityflow-project/CityFlow/files/4406117/traffic_flow.txt)
[roadnet.txt](https://github.com/cityflow-project/CityFlow/files/4406118/roadnet.txt)
 
I appreciate any help or comment.

**Comment by soodoshll** [comment]
Hi, I've tried to run the config files with the latest code and I found one problem in the file `roadnet.txt`, that is in the definition of "road_1_1_3", the `endIntersection` of it is "intersection_1_0" (line 327), but I can't find the definition of "intersection_1_0".

We should add a check for such problems. Thank you!

**Comment by oroojlooy** [comment]
Thanks!
This solved the issue. 
May I know how did you find the issue? Is there any way to debug the C++ code?

**Comment by soodoshll** [comment]
Yes, there is a  [C++ example](https://github.com/cityflow-project/CityFlow/blob/master/tools/debug/simple_run.cpp). A debugger can tell where an error occurs.

**Comment by oroojlooy** [comment]
Thanks!
