### ISSUE TITLE
One-lane roads with straight and allowed turn-left traffic movements 

### ISSUE THREAD

**Issue by oroojlooy** [cityflow-project/CityFlow#83]
I was wondering if CityFlow support the case that there are single lane in a three/four-way intersections in which turn-left is allowed. In other words, does it support the case that one lane can have both straight and turn-left traffic movements? If so, would you mind let me know how can I create the `roadnet.json` file? 
I attached two drawing examples of the corresponding intersections:
[four_roads.pdf](https://github.com/cityflow-project/CityFlow/files/4417049/four_roads.pdf)
[three_roads.pdf](https://github.com/cityflow-project/CityFlow/files/4417050/three_roads.pdf)

Thanks in advance,
Afshin

**Comment by only-changer** [comment]
Yes,  one lane can have multi movements in CItyflow.  You just need to define it as the "roadlink" features of "intersection", in roadnet.json; 
For example, check this Atlanta roadnet https://github.com/traffic-signal-control/sample-code/blob/master/data/atlanta_1x5/roadnet_atlanta.json
Search for "startRoad": "9246225#4,  you can see this road has only one lane but can both go straight and turn left.

**Comment by oroojlooy** [comment]
Thanks for clarification!.
