### ISSUE TITLE
Turn-Right traffic on two lane road

### ISSUE THREAD

**Issue by oroojlooy** [cityflow-project/CityFlow#88]
I was wondering if it is valid to have turn-right traffic in an intersection that each of its roads have two lanes, one `straight` and one `left`? 
In the real-world, usually, in the straight-only lanes cars are allowed to turn light on the green signal. I was not sure if it is considered in the CityFlow or not.

**Comment by only-changer** [comment]
Yes, you can implement by 1. add the road links to turn right in a go straight lane. 2. set this movement always to be a green light.

**Comment by oroojlooy** [comment]
Thanks for clarification!.
