### ISSUE TITLE
Error viewing replay with CityFlow (console.log showing roadnet is undefined)

### ISSUE THREAD

**Issue by kclim2** [cityflow-project/CityFlow#94]
i managed to use CityFlow to test the replay with the example at https://github.com/cityflow-project/data/tree/master/frontend/replay

however, i get the error message "roadnet is undefined" when trying with roadnet_6_6.json used by coLight https://github.com/wingsweihua/colight/tree/master/data/template_lsr/6_6

the content in both the json file looks kind of different.

**Comment by only-changer** [comment]
The input roadnet and output roadnet of CityFlow are different. You should use the output roadnet of Cityflow in the replay website index.html.
