### ISSUE TITLE
How to find the waiting time for each vehicle on the particular lane.

### ISSUE THREAD

**Issue by samta** [cityflow-project/CityFlow#98]
There is api to find the number of wait vehicle in a lane (self.eng.get_lane_waiting_vehicle_count()), but in order to design a different reward, I would like to find waiting time for each vehicle.
Can somebody pls point out to the right api/way to achieve it.

**Comment by only-changer** [comment]
For now, we don't have such an API, you can modify "src/cityflow.cpp" and re-compile the C++ code to add one.
